apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ include "namespace" . }}

spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  strategy:
    type: {{ .Values.deployment.spec.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.spec.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deployment.spec.strategy.rollingUpdate.maxSurge }}
 
  selector:
    matchLabels:
      app: {{ .Values.deployment.spec.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.spec.selector.matchLabels.app }}

    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ .Values.nginx.cm_name }}
          items:
          - key: {{ .Values.configMapKey }}
            path: {{ .Values.configMapPath }}
      - name: {{ .Values.persistentVolumeClaim.name }}
        persistentVolumeClaim:
          claimName:  {{ .Values.persistentVolumeClaim.name }}
      - name: {{ .Values.nginx.cm_name }}
        configMap:
          name: {{ .Values.nginx.cm_name }}
      
      initContainers:
      - name: init-container
        image: busybox:stable
        command: ['sh', '-c', echo 'Hello!'   > /init/index.html]
        volumeMounts:
        - name:  {{ .Values.persistentVolumeClaim.name }}
          mountPath: /init
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.deployment.nodeSelector.hostname }}
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name:  {{ .Values.persistentVolumeClaim.name }}
          mountPath: /homework
        - name: {{ .Values.nginx.cm_name }}
          mountPath: /homework/conf/file
        {{- if .Values.probes.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'test -f /homework/index.html'
        {{- end }}
        {{- if .Values.lifecycle.preStop.enabled }}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "rm -f /homework/index.html"]
        {{- end }}
