apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.cm_name }}
  namespace: {{ include "namespace" . }}
data:
  default.conf: |
    server {
        listen {{ .Values.service.port }};
        server_name localhost;

        location / {
            root /homework;
            index index.html index.htm;
            autoindex on;
        }
    }
