apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv55
  namespace: {{ include "namespace" . }}
  labels:
    type: local
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.118
    path: /mnt/nfsdir
