apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ include "namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
