---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-clusterrole
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  resourceNames: ["mysql.otus.homework"]
  verbs: ["get", "list", "watch", "update", "patch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "update"]

- apiGroups: [""]
  resources: ["deployment","services", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-binding
subjects:
- kind: ServiceAccount
  name: mysql-operator-sa
  namespace: homework
roleRef:
  kind: ClusterRole
  name: mysql-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
