apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: homework

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /homework/index.html
spec:
  rules:
  - host: homework.otus
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-service
            port:
              number: 8000
      - pathType: Prefix
        path: "/homepage"
        backend:
          service:
            name: my-service
            port:
              number: 8000
