---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-distroless-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx-distroless
        image: kyos0109/nginx-distroless
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        securityContext:
          seccompProfile:
            type: Unconfined
      restartPolicy: Always

#kubectl debug -it nginx-distroless-deployment-79764f76bc-fhrpc  --image=busybox  --target=nginx-distroless
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
