apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-homework
  namespace: homework
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}

      initContainers:
        - name: init-container
          image: busybox:stable
          command: ['sh', '-c', 'ls /init/ > /init/index.html']
          volumeMounts:
            - name: shared-volume
              mountPath: /init
      nodeSelector:
        kubernetes.io/hostname: worker3
      containers:
        - name: main-container
          image: python:3.9-slim
          command: ["python3", "-m", "http.server", "8000", "--directory", "/"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-volume
              mountPath: /homework
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - 'test -f /homework/index.html'
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "rm -f /homework/index.html"]
