apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/name: my-ingress
    app.kubernetes.io/component: controller
