apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: homework
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html/;
        index index.html;
        location = /stub_status
        {
          stub_status;
        }
    }
