apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: homework
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-configmap
          items:
          - key: default.conf
            path: default.conf

      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.4.1
        args:
        - "--nginx.scrape-uri=http://localhost:8080/stub_status"
        ports:
        - containerPort: 9113
