---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: homework

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-read-metrics
  namespace: homework
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-read-metrics-binding
  namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-read-metrics
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: homework

