---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: homework
  labels:
    app: nginx-exporter
    app.kubernetes.io/part-of: dms
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 8080


