apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv3
  namespace: homework
  labels:
    type: local
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
#  persistentVolumeReclaimPolicy: Delete
  storageClassName: my-storageclass
  nfs:
    server: 192.168.1.118
    path: /mnt/nfsdir
