releases:
  - name: kafka
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 32.1.3
    namespace: dev
    values:
      - dev.yaml

  - name: kafka
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 32.1.3
    namespace: prod
    values:
      - prod.yaml
